### ISSUE TITLE
Integrals missing in the pyscf to trexio converter

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio_tools#29]
Hello @kousuke-nakano,

I wanted to use the pyscf -> trexio converter but then I noticed that 1- and 2-electron integrals are not written in the TREXIO file. This poses a lot of limitations as we cannot use the resulting TREXIO file for some applications. 

Would it be possible to write also 1- and 2-e integrals from PySCF?

**Comment by kousuke-nakano** [comment]
Dear @q-posev, yes, I think it's possible. I remember I implemented it but did not commit it because there was some problem in the normalization. Let me try it again.

**Comment by kousuke-nakano** [comment]
Oh, sorry, I will do this...

**Comment by q-posev** [comment]
TREXIO interface has been recently implemented in the PySCF-forge, see [this PR](https://github.com/pyscf/pyscf-forge/pull/60). I can see that integral dumping and reading has been added too.

@kousuke-nakano when you have some time, could you please check if the normazation issues mentioned above have been fixed in this PySCF PR or not? If yes, then perhaps we can use directly the TREXIO writer in PySCF?

**Comment by kousuke-nakano** [comment]
Dear @q-posev, great news !!!

> @kousuke-nakano when you have some time, could you please check if the normalization issues mentioned above have been fixed in this PySCF PR or not?

Yes, sure! 

> coef = [mol.bas_ctr_coeff(i).ravel() for i in range(mol.nbas)]
> prim_norms = [gto.gto_norm(mol.bas_angular(i), mol.bas_exp(i)) for i in range(mol.nbas)]
> trexio.write_basis_shell_factor(trexio_file, np.ones(mol.nbas))

I think their implementation is fine. It seems that the primitive normalization factors are correctly considered. They set 1.0 for the shell normalization factors. I think it should be ok because the shell normalizations, which are different from 1.0 for contracted orbitals, are already included in the prim. normalization factors taken from `bas_ctr_coeff()`.

> If yes, then perhaps we can use directly the TREXIO writer in PySCF?

`ecp == True` cases are not implemented in [this PR](https://github.com/pyscf/pyscf-forge/pull/60). This is practically quite important. I can easily do it as I have already implemented it to `trexio-tool`. Shall I make a pull request to the pySCF-forge?

**Comment by scemama** [comment]
> *ecp == True* cases are not implemented in this PR[https://github.com/pyscf/pyscf-forge/pull/60]. This is practically quite important. I can easily do it as I have already implemented it to *trexio-tool*. Shall I make a pull request to the pySCF-forge?
>

Yes! That would be great!
