### ISSUE TITLE
PySCF to TREXIO converter is broken

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio_tools#31]
@kousuke-nakano GitHub CI is failing to convert from PySCF to TREXIO in the latest [CI](https://github.com/TREX-CoE/trexio_tools/pull/30/checks). Can you have a look at it?

**Comment by kousuke-nakano** [comment]
Dear @q-posev, yes, sure I am trying to fix it now.

**Comment by kousuke-nakano** [comment]
Dear @q-posev, OK, I got it. The problem seems to be due to the major update of PySCF. I generated the PySCF checkpoint files using v2.0.1. It seems compatible with versions up to v2.3.0 (#54), while PySCF-2.4.0 installed in the failed workflow (#60) cannot read it correctly. Let's replace the checkpoint files with those generated by the latest version or install PySCF < = 2.3.0 in the workflow.

**Comment by q-posev** [comment]
Dear @kousuke-nakano,
Thanks for having a look so fast!

If you want, we can generate PySCF checkpoint files in the CI too. Is it a lot of work to make the converter compatible with the latest PySCF? We can do an `if/else` to execute different code depending on PySCF version. Let me know what you prefer.

**Comment by kousuke-nakano** [comment]
Dear @q-posev Sorry for my late reply. I have fixed this bun in #32. 

> If you want, we can generate PySCF checkpoint files in the CI too. 

I think it is possible for `water.chk`, but not for `diamond.chk` since the PBC calculations are too heavy to do in the CI.
So, it seems better to add an `if/else` to execute different code depending on PySCF version
